site_name: MST-AUGer
theme: readthedocs

nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Augmentation: 'augmentation.md'
    - Evaluation: 'evaluation.md'
    - About: 'about.md'
